-- Categories, in display order
insert into categories (nom, emoji, ordre) values
  ('Formules', '✨', 1),
  ('Paninis', '🥖', 2),
  ('Wraps', '🌯', 3),
  ('Bagels', '🥯', 4),
  ('Toasty', '🥪', 5),
  ('Salades', '🥗', 6),
  ('Pâtes et Plats', '🍝', 7),
  ('Frites', '🍟', 8),
  ('Smoothies', '🥛', 9),
  ('Milkshakes & Frappés & Freakshakes', '🐄', 10),
  ('Gaufres & Crêpes', '🧇', 11),
  ('Pâtisseries & Spécialités Américaines', '🍩', 12),
  ('Boissons Soft & Chaudes', '🥤', 13),
  ('Glaces Artisanales', '🍦', 14);

with cat as (select id, nom from categories)
insert into produits (categorie_id, nom, description, prix_centimes, disponible, ordre)
select cat.id, v.nom, v.description, v.prix_centimes, v.disponible, v.ordre
from (values
  -- Formules (menus à emporter)
  ('Formules', 'Menu Pâtes Emporter', 'Pâtes, boisson et dessert', 1390, true, 1),
  ('Formules', 'Menu Salade Emporter', 'Salade, boisson et dessert', 1190, true, 2),
  ('Formules', 'Menu Panini & Wraps', 'Panini ou Wrap, boisson et dessert', 850, true, 3),
  ('Formules', 'Menu Bagel & Toasty', 'Bagel ou Toasty, boisson et dessert', 890, true, 4),
  -- Paninis
  ('Paninis', 'Panini Indien', 'Curry, mozzarella & émincés de poulet', 490, true, 1),
  ('Paninis', 'Panini Oriental', 'Sauce samouraï, mozzarella & poulet', 490, true, 2),
  ('Paninis', 'Panini 3 Fromages', 'Mozzarella, cheddar & chèvre', 490, true, 3),
  ('Paninis', 'Panini Saumon', 'Crème cheese, mozzarella, saumon fumé', 490, true, 4),
  -- Bagels
  ('Bagels', 'Bagel Poulet', 'Bagel recouvert de cheddar irlandais, crème, poulet', 590, true, 1),
  ('Bagels', 'Bagel Avocado (poulet guacamole)', 'Bagel recouvert de cheddar irlandais, crème, poulet, guacamole', 690, true, 2),
  ('Bagels', 'Bagel Saumon', 'Pain bagel recouvert de graines de sésame, saumon', 590, true, 3),
  ('Bagels', 'Bagel Green Smith (saumon guacamole)', 'Pain bagel recouvert de graines de sésame, saumon, guacamole', 690, true, 4),
  -- Toasty
  ('Toasty', 'Toasty Poulet Curry', 'Sauce curry, oignons frits, mozzarella & émincés de poulet', 590, true, 1),
  ('Toasty', 'Toasty Poulet Samouraï', 'Sauce samouraï, oignons frits, mozzarella & émincés de poulet', 590, true, 2),
  -- Salades (descriptions tronquées dans l'app source elle-même)
  ('Salades', 'Salade César', 'Salade verte, émincés de poulet, oignons frits...', 990, true, 1),
  ('Salades', 'Salade Océane', 'Salade verte, saumon fumé, tomates, croutons...', 990, true, 2),
  -- Pâtes et Plats
  ('Pâtes et Plats', 'Pâtes Penne', '', 990, true, 1),
  ('Pâtes et Plats', 'Pâtes Fusilli', '', 990, true, 2),
  ('Pâtes et Plats', 'Pâtes Conchiglie', '', 990, true, 3),
  -- Frites
  ('Frites', 'Frites', 'Frites 100g', 250, true, 1),
  -- Smoothies (35cl sauf mention contraire)
  ('Smoothies', 'Smoothie Fantasy 35cl', 'Fraise & banane, jus de pomme', 590, true, 1),
  ('Smoothies', 'Smoothie Sunset 35cl', 'Ananas, mangue & papaye, jus de pomme', 590, true, 2),
  ('Smoothies', 'Smoothie Heaven 35cl', 'Framboise, myrtille, mangue & pomme, jus de...', 590, true, 3),
  ('Smoothies', 'Smoothie Caraïbes 35cl', 'Ananas, fraise & coco, jus de pomme', 750, true, 4),
  ('Smoothies', 'Smooth Bubble', 'Smoothie parfum au choix et perle de tapioca', 690, true, 5),
  ('Smoothies', 'Smoothie Green Reviver 35cl', 'Mangue, banane, citronnelle, chou, jus de...', 590, true, 6),
  ('Smoothies', 'Smoothie Coconut 35cl', 'Ananas, lait de coco, jus de pomme', 590, true, 7),
  ('Smoothies', 'Smoothie Sweet Berry 35cl', 'Mûre, fraise, framboise', 590, true, 8),
  -- Milkshakes & Frappés & Freakshakes (typos "Milshake" du menu source normalisées en "Milkshake")
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Vanille', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 1),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Shtroumpf', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 2),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Fraise', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 3),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Passion', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 4),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Chocolat', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 5),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Caramel', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 6),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Café', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 7),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Licorne', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 8),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Citron', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 9),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Pistachio', 'À base de glace artisanale, lait, chantilly incluse', 650, true, 10),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Barbapapa', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 11),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Twister', 'Fraise, citron, citron vert, ananas', 550, true, 12),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Framboise', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 13),
  ('Milkshakes & Frappés & Freakshakes', 'Milkshake Chewing-gum', 'À base de glace artisanale, lait, chantilly incluse', 550, true, 14),
  ('Milkshakes & Frappés & Freakshakes', 'Bubble Shake', 'Milkshake parfum au choix et perle de tapioca', 650, true, 15),
  ('Milkshakes & Frappés & Freakshakes', 'Frappé Banane', 'À base de glace artisanale, lait, chantilly incluse', 590, true, 16),
  ('Milkshakes & Frappés & Freakshakes', 'Frappé Oréo', 'Glace vanille, oréo, lait, crème fouettée & topping...', 590, true, 17),
  ('Milkshakes & Frappés & Freakshakes', 'Frappé Bueno', 'Glace vanille, Kinder Bueno, lait, crème fouettée...', 590, true, 18),
  ('Milkshakes & Frappés & Freakshakes', 'Frappé M&M''s', 'Glace vanille, M&M''s, lait, crème fouettée & topping...', 590, true, 19),
  ('Milkshakes & Frappés & Freakshakes', 'Frappé Spéculoos', 'Glace vanille, Spéculoos, lait, crème fouettée & ...', 590, true, 20),
  ('Milkshakes & Frappés & Freakshakes', 'Freakshake Bueno', 'Glace vanille, Kinder Bueno, lait, crème fouettée & topping...', 790, true, 21),
  ('Milkshakes & Frappés & Freakshakes', 'Freakshake M&M''s', 'Glace vanille, M&M''s, lait, crème fouettée & topping...', 790, true, 22),
  ('Milkshakes & Frappés & Freakshakes', 'Freakshake Spéculoos', 'Glace vanille, Spéculoos, lait, crème fouettée & ...', 790, true, 23),
  ('Milkshakes & Frappés & Freakshakes', 'Freakshake Oréo', 'Glace vanille, oréo, lait, crème fouettée & topping...', 790, true, 24),
  -- Gaufres & Crêpes
  ('Gaufres & Crêpes', 'Gaufre Nature', '', 490, true, 1),
  ('Gaufres & Crêpes', 'Gaufre Nutella Banane', 'Gaufre de Liège Nutella + banane', 490, true, 2),
  ('Gaufres & Crêpes', 'Gaufre Crème Spéculoos', '', 550, true, 3),
  ('Gaufres & Crêpes', 'Gaufre Nutella Bueno', 'Gaufre de Liège Nutella Bueno', 490, true, 4),
  ('Gaufres & Crêpes', 'Gaufre Nutella', 'Gaufre de Liège Nutella', 550, true, 5),
  ('Gaufres & Crêpes', 'Gaufre Sucre', 'Gaufre de Liège Sucre', 350, true, 6),
  ('Gaufres & Crêpes', 'Gaufre Nutella Oréo', 'Gaufre de Liège Nutella Oréo', 490, true, 7),
  ('Gaufres & Crêpes', 'Gaufre Crème Bueno', 'Gaufre Crème Bueno', 390, true, 8),
  ('Gaufres & Crêpes', 'Gaufre Pistache', '', 450, true, 9),
  ('Gaufres & Crêpes', 'Crêpe Nature', '', 320, true, 10),
  ('Gaufres & Crêpes', 'Crêpe Crème Spéculoos', '', 450, true, 11),
  ('Gaufres & Crêpes', 'Crêpe Nutella Bueno', 'Nutella + Kinder Bueno', 490, true, 12),
  ('Gaufres & Crêpes', 'Crêpe Nutella Banane', 'Banane + Nutella', 490, true, 13),
  ('Gaufres & Crêpes', 'Crêpe Crème Bueno', '', 450, true, 14),
  -- Pâtisseries & Spécialités Américaines
  ('Pâtisseries & Spécialités Américaines', 'Muffin Pistache', '', 350, true, 1),
  ('Pâtisseries & Spécialités Américaines', 'Muffin Fruits Rouges', 'Fourré fruits rouges', 350, false, 2),
  ('Pâtisseries & Spécialités Américaines', 'Muffin Caramel', '', 350, true, 3),
  ('Pâtisseries & Spécialités Américaines', 'Muffin Chocolat', 'Fourré fondant chocolat', 350, true, 4),
  ('Pâtisseries & Spécialités Américaines', 'Muffin Nutella', 'Fourré Nutella', 450, true, 5),
  ('Pâtisseries & Spécialités Américaines', 'Muffin Myrtilles', 'Fourré myrtilles', 350, false, 6),
  ('Pâtisseries & Spécialités Américaines', 'Brownie', 'Brownie noix de pécan', 450, true, 7),
  ('Pâtisseries & Spécialités Américaines', 'Brookie', 'Mi cookie / mi brownie', 450, true, 8),
  ('Pâtisseries & Spécialités Américaines', 'Cookie Fourré', '', 290, true, 9),
  ('Pâtisseries & Spécialités Américaines', 'Cookie Cacao Fourré Dubaï Pistache', '', 290, true, 10),
  ('Pâtisseries & Spécialités Américaines', 'Cookie Cranberry Chocolat Blanc', '', 290, true, 11),
  ('Pâtisseries & Spécialités Américaines', 'Cookie Cacahuète Caramel', '', 290, false, 12),
  ('Pâtisseries & Spécialités Américaines', 'Donut Classic', 'Parfums divers', 220, true, 13),
  ('Pâtisseries & Spécialités Américaines', 'Donut Suprême', 'Parfums divers', 350, true, 14),
  ('Pâtisseries & Spécialités Américaines', 'Coulant Chocolat', '', 390, false, 15),
  ('Pâtisseries & Spécialités Américaines', 'Cheesecake Myrtilles', 'Cheesecake composé d''une couche de biscuits...', 390, true, 16),
  ('Pâtisseries & Spécialités Américaines', 'Red Velvet', 'Layer cake façon Red Velvet composé de...', 490, true, 17),
  ('Pâtisseries & Spécialités Américaines', 'Cheesecake Bueno', 'Cheesecake composé d''une couche de biscuits...', 490, true, 18),
  ('Pâtisseries & Spécialités Américaines', 'Cheesecake Spéculoos', 'Cheesecake composé d''une couche de biscuits...', 490, true, 19),
  ('Pâtisseries & Spécialités Américaines', 'Tarte à la Framboise', '', 290, false, 20),
  ('Pâtisseries & Spécialités Américaines', 'Tarte Citron Meringuée', '', 290, false, 21),
  ('Pâtisseries & Spécialités Américaines', 'Tiramisu', '', 390, false, 22),
  ('Pâtisseries & Spécialités Américaines', 'Tarte au Chocolat', '', 290, false, 23),
  ('Pâtisseries & Spécialités Américaines', 'Tarte aux Pommes', '', 290, true, 24),
  ('Pâtisseries & Spécialités Américaines', 'Tarte au Flan', '', 290, false, 25),
  ('Pâtisseries & Spécialités Américaines', 'Flan Cookie', '', 290, true, 26),
  -- Boissons Soft & Chaudes
  ('Boissons Soft & Chaudes', 'Lipton Pêche 33cl', '', 250, true, 1),
  ('Boissons Soft & Chaudes', 'Orangina 33cl', '', 250, true, 2),
  ('Boissons Soft & Chaudes', 'Oasis Tropical 33cl', '', 250, true, 3),
  ('Boissons Soft & Chaudes', 'Oasis Cassis / Framboise 33cl', '', 250, true, 4),
  ('Boissons Soft & Chaudes', 'Dada Cola 33cl', '', 250, true, 5),
  ('Boissons Soft & Chaudes', 'Dada Cola Zéro Sucre 33cl', '', 250, true, 6),
  ('Boissons Soft & Chaudes', 'Eau Plate Cristaline 50cl', '', 200, true, 7),
  ('Boissons Soft & Chaudes', 'Perrier 33cl', '', 250, true, 8),
  ('Boissons Soft & Chaudes', 'Red Bull', '', 300, true, 9),
  ('Boissons Soft & Chaudes', 'Expresso', '', 200, true, 10),
  ('Boissons Soft & Chaudes', 'Double Expresso', '', 350, true, 11),
  ('Boissons Soft & Chaudes', 'Expresso Crème', '', 220, true, 12),
  ('Boissons Soft & Chaudes', 'Café Latté', '', 350, true, 13),
  ('Boissons Soft & Chaudes', 'Cappuccino', '', 450, true, 14),
  ('Boissons Soft & Chaudes', 'Allongé', '', 250, true, 15),
  ('Boissons Soft & Chaudes', 'Chocolat Chaud', '', 450, true, 16)
) as v(cat_nom, nom, description, prix_centimes, disponible, ordre)
join cat on cat.nom = v.cat_nom;

-- A demo table for local testing
insert into tables (numero, slug) values (1, 'table-1');
